name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libwayland-dev \
            wayland-protocols \
            libxkbcommon-dev \
            wget \
            git

      - name: Build
        run: |
          make -j$(nproc)
