name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed \
            git \
            base-devel \
            hyprland \
            pixman \
            libdrm \
            pkgconf

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix git ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: |
          make -j$(nproc)

